### ISSUE TITLE
[RESOLVED] API key gives invalid response

### ISSUE THREAD

**Issue by Leejit** [SalmonDE/TopVoter#10]
To be honest, and I apologize... I didn't think StatsPE & TopVoter (Two beautiful plugins I use !) were both yours. 

Well, this is the plugin I'm having issues with ... I get a "invalid response" from the server, when configured the exact same on Tess as was on PocketMine. 

Any help ? I can show you a screen shot, or directly get some log clips of the error.

**Comment by Leejit** [comment]
**Removed API-Key due to security reasons - Salmon**

**Comment by Leejit** [comment]
lol, t.y Salmon.... but how is it a security risk ? j.w. :$

**Comment by SalmonDE** [comment]
@LordJoshie As far as I know the serverlist claimed that you should never post it somewhere. Anyway, it seems like your API key is invalid.

**Comment by SalmonDE** [comment]
I'll try to make the plugin show the response of the serverlist

**Comment by Leejit** [comment]
:'(  but its what i use for vote rewards. wubwub. t.y for the help. sorry
im at work atm, i seem derpy cuz Im typing quick xD

Ill try solutions after work. :$

**Comment by SalmonDE** [comment]
@LordJoshie Try using this link:
https://minecraftpocket-servers.com/api/?object=servers&element=voters&month=current&format=json&key= **insert-your-key-here!**

**Comment by Leejit** [comment]
you suggest I use the whole link with my key in the spot without the *'s ?

**Comment by SalmonDE** [comment]
@LordJoshie you can test your key with that link. It won't make it work, I just wanted to tell you how I tested it.

**Comment by Leejit** [comment]
Oh, thanks ! Ill use this to try and solve my issue.

I appreciate the help. Id have tried these steps before asking for help,
but I wasnt aware until now.

Ill give this all a try later. Thank you !

**Comment by SalmonDE** [comment]
Hope this won't happen again! :) Added a console message to let people know if their API key is invalid.

**Comment by Leejit** [comment]
Thanks Salmon ! I appreciate your help here.

**Comment by Leejit** [comment]
Hey Salmon, I am home from work now and able to provide anything from my end needed for you to help me resolve this issue... 

And my apologies about lastnights/thismornings little messup with the plugin confusion... I was super tired :P

**Comment by Leejit** [comment]
![capture](https://cloud.githubusercontent.com/assets/17371144/22674052/d4e121b6-ecab-11e6-8fe8-9233aca35219.PNG)

**Comment by Leejit** [comment]
after you updated the plugin, this was the new information it gave me... if there is a way I can personally show you my logs and .yml's to compare, and for you to point out what my problem is, I am all for doing that, so my personal information isn't shared here in a public place.

**Comment by Aericio** [comment]
You could contact him via [Telegram](https://telegram.me/SalmonDE) or email him (salmonde@salmonde.de)

**Comment by Aericio** [comment]
Oh, try resetting your config.yml for TopVoter and type everything back in (don't cp). I am not sure if this matters, but make sure there is no space in the begging or the end inside the `API-Key: 'supersecretkey'`

**Comment by LordJoshie** [comment]
![capture](https://cloud.githubusercontent.com/assets/17371144/22682537/219bc1a2-ece1-11e6-829e-eaec77856b48.PNG)

**Comment by Leejit** [comment]
I don't care much about the api-key being shown, but here... I downloaded Tess, I downloaded TopVoter, and ran it... still get the same issue. so I'm stupid :) 
![capture](https://cloud.githubusercontent.com/assets/17371144/22682571/5777b056-ece1-11e6-9222-6dc08484ee26.PNG)

**Comment by Leejit** [comment]
Sorry to be a bother Salmon, I've literally gone through this way more than I ever thought I would. 

With my very small amount of knowledge, I went ahead and picked apart the plugin and it seems that no matter what I do, I will always receive the same errors. 

:S

**Comment by Leejit** [comment]
As you can see here, with some changes to the source plugin, and a test on Tesseract, it DOES in fact work.... however, something due to the way the plugin is calling to/handling the information is the issue I'm having. 

Have you made any changes in the past Salmon ?



![capture1](https://cloud.githubusercontent.com/assets/17371144/22687020/6165b3a2-ecf4-11e6-84a7-997f6a5e9627.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17371144/22687021/616ff04c-ecf4-11e6-8a6d-725bb90dad5e.PNG)

**Comment by SalmonDE** [comment]
@LordJoshie Yup, I also came to the same solution when I saw that the Updater also failed for you. It seems like the way the plugin connects to the internet is broken. I'll guess the Utils::getURL() function has to do with this issue.

**Comment by Leejit** [comment]
Hey.... Salmon, my friend and I figured it out. 

ALL CREDIT GOES TO MY FRIEND... but change the https to just be http. wallah. have a good day.

**Comment by SalmonDE** [comment]
@LordJoshie In normal cases https shouldn't cause such issues. But I can't offer another solution yet, so I'll close this now.

**Comment by Leejit** [comment]
Hey man, if it ain't broke... don't fix it !

And fortunately, you're plugin wasn't broken... just the laws of the internet... so we had to lie a little. :)

**Comment by SalmonDE** [comment]
@LordJoshie I asked dktapps about a feature which could return the cURL error in Utils::getURL(). I hope the idea gets accepted. That could help to truly find out what this issue was caused by.

**Comment by SalmonDE** [comment]
The feature was added into the branch [issues/332](https://github.com/pmmp/PocketMine-MP/tree/issues/332) at pmmp. As soon as the updater crash of pmmp is fixed, could you test this again with this version of pmmp? I am really interested to fix this issue or just find out, what the cause was.

**Comment by Leejit** [comment]
Yeah, I'll give this a go now and report my findings.

**Comment by Leejit** [comment]
I realize why I don't use PocketMine, besides having nothing to offer, it's slow, uses too much resource, and you need to compile the spl/raklib& lang files... holy garbage.

My server is currently frozen because of launching PocketMine. doesn't help I'm doing this off the server I host my public server on... so... whoops.

**Comment by SalmonDE** [comment]
@LordJoshie Oh well, I'd always suggest to test things on a test server. Do you need a phar compiled or will you be able to compile from branch issues/332?

Oh and the thing is, you're actually supposed to recursivly download the repository (git clone --recursive https://github.com/pmmp/PocketMine-MP should work). This way submodules will be downloaded, too.

**Comment by Leejit** [comment]
its compiled... derp. hence when booting it lagged the shit out of my server. 

also, I only own one vps... so I create new folders for my test servers... not expecting a program that is default set to use only 512mb of ram, to take up 3gb fro a world generation, and lag up my vps so hard... 

still waiting for a response from it.

**Comment by Leejit** [comment]
Okay, things are fine now...

Regardless, I'm still curious why this needs to be tested... or what you're expecting to get from it.

**Comment by SalmonDE** [comment]
@LordJoshie Since I didn't change anything or fix it it could be possible that other people could encounter this issue. If it is avoidable by the code I'd like to change it properly.

I hope Utils::getURL() will return an error message from cURL. It should do with the new pmmp branch when cURL fails.

**Comment by SalmonDE** [comment]
Seems to be connected to #26 in retrospective.
