### ISSUE TITLE
I think u forget the Updater :)

### ISSUE THREAD

**Issue by hqn21** [SalmonDE/TopVoter#15]

**Comment by SalmonDE** [comment]
Hmm, yeah the updater usually only allows one update per day but I could do an exception this time.

**Comment by hqn21** [comment]
OKAY :)

**Comment by SalmonDE** [comment]
It should update now

**Comment by hqn21** [comment]
tks u are nice

**Comment by SalmonDE** [comment]
Nevermind. Travis failed so there wasn't any update made yet. I need to update DevTools. ugh
