### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ghost** [SalmonDE/TopVoter#16]
[Tesseract] [16:58:41] ERROR> [TopVoter] Couldn't process data! No array was returned!
[Tesseract] [16:58:41] ERROR> [TopVoter] Raw:

@SalmonDE

**Comment by SalmonDE** [comment]
Could tell me what you get from visiting this url on your server machine? Oh, and don't forget to insert the API key at the end. :)
https://minecraftpocket-servers.com/api/?object=servers&element=voters&month=current&format=json&limit=5&key=[YOUR-API-KEY]

**Comment by hqn21** [comment]
@SalmonDE I have the same problem
I'm sure i enter the API KEY into config.yml :)))))))))))))))))))))))))

**Comment by SalmonDE** [comment]
Could you try the same as above? And if you wouldn't mind, I think an E-Mail conversation would be faster and more reliable. ;) Contact me at salmonde@salmonde.de

**Comment by EndreEndi** [comment]
@NycuRO for me working this plugin:)

**Comment by Ishannaik** [comment]
same issue not working for me
when i did the link of the api key
this one https://minecraftpocket-servers.com/api/?object=servers&element=voters&month=current&format=json&limit=500&key=[YOUR-API-KEY]
```
{ "name":"InPocket", "address":"inpocketpe.ddns.net", "port":"19132", "month":"201703", "voters": [ { "nickname":"Ishannaik", "votes":"17" },	{ "nickname":"lavaboy1216", "votes":"9" },	{ "nickname":"Khasikage", "votes":"6" },	{ "nickname":"IRANKING224477", "votes":"3" },	{ "nickname":"BjornNL14", "votes":"2" },	{ "nickname":"PlayerMan2015", "votes":"2" },	{ "nickname":"antonyFTPake ", "votes":"1" },	{ "nickname":"ThatDonutCookie", "votes":"1" },	{ "nickname":"VigorousCow70", "votes":"1" },	{ "nickname":"Duckiedaderpy ", "votes":"1" },	{ "nickname":"Wolfalpha ", "votes":"1" },	{ "nickname":"NewSepticPro", "votes":"1" },	{ "nickname":"Spring4Life", "votes":"1" },	{ "nickname":"IamDabbingStone", "votes":"1" },	{ "nickname":"KingPheonixXYZ", "votes":"1" },	{ "nickname":"BIOHUNTER", "votes":"1" },	{ "nickname":"DUh_ITS_PATHER", "votes":"1" },	{ "nickname":"Swag_Lord", "votes":"1" },	{ "nickname":"Genetix", "votes":"1" },	{ "nickname":"YoutubeJLT_YT", "votes":"1" },	{ "nickname":"girl8876", "votes":"1" },	{ "nickname":"TWSmiles", "votes":"1" },	{ "nickname":"WAJEEH203_YT", "votes":"1" },	{ "nickname":"jonjon", "votes":"1" },	{ "nickname":"Foxyxx376", "votes":"1" },	{ "nickname":"Musical_Rachel", "votes":"1" },	{ "nickname":"ShawnOboy", "votes":"1" },	{ "nickname":"Abdumalik15", "votes":"1" },	{ "nickname":"Anonymouse10638", "votes":"1" },	{ "nickname":"Mcwad56", "votes":"1" },	{ "nickname":"AlexKnight", "votes":"1" },	{ "nickname":"XFactorLive", "votes":"1" },	{ "nickname":"LukeDoezMC", "votes":"1" },	{ "nickname":"DrepTheDino", "votes":"1" },	{ "nickname":"NINJA_235", "votes":"1" },	{ "nickname":"mike000041", "votes":"1" },	{ "nickname":"PartsPirate", "votes":"1" },	{ "nickname":"ThoughtSauce877 ", "votes":"1" },	{ "nickname":"Yair2099 ", "votes":"1" },	{ "nickname":"Shqdow7o7", "votes":"1" },	{ "nickname":"Natasha_Chan", "votes":"1" },	{ "nickname":"Supersaiyam", "votes":"1" },	{ "nickname":"SakurakoSaki", "votes":"1" },	{ "nickname":"cute_tom", "votes":"1" },	{ "nickname":"Eibil_GameYT", "votes":"1" },	{ "nickname":"JamesXGhoul", "votes":"1" },	{ "nickname":"KCKawaiiKid_Saki", "votes":"1" },	{ "nickname":"Thunder4359", "votes":"1" },	{ "nickname":"ISkyTryk", "votes":"1" },	{ "nickname":"EnderDragonXfire", "votes":"1" },	{ "nickname":"Jorti1boombox", "votes":"1" },	{ "nickname":"WaterPlanet323", "votes":"1" },	{ "nickname":"Ishan", "votes":"1" },	{ "nickname":"GoldenXPlayz", "votes":"1" },	{ "nickname":"DeathReaper655", "votes":"1" },	{ "nickname":"BluBeryyy", "votes":"1" },	{ "nickname":"Xxopmike778Xx", "votes":"1" },	{ "nickname":"XXMak_Is_BackXx", "votes":"1" },	{ "nickname":"NewYorkFan123", "votes":"1" },	{ "nickname":"ALPHAERDE45", "votes":"1" },	{ "nickname":"MQueenM", "votes":"1" },	{ "nickname":"NiceTheaKing", "votes":"1" },	{ "nickname":"XxRaphaxX", "votes":"1" },	{ "nickname":"ArthurTheMightyP", "votes":"1" },	{ "nickname":"happyman55552", "votes":"1" },	{ "nickname":"Viper2232", "votes":"1" },	{ "nickname":"_Robert03_", "votes":"1" }	] }
```
but the console shows
```
[Tesseract] [05:31:01] WARNING> [TopVoter] Error while processing data from the serverlist!
[Tesseract] [05:31:01] ERROR> [TopVoter] Couldn't process data! No array was returned!
[Tesseract] [05:31:01] ERROR> [TopVoter] Raw: Error: no server key
[Tesseract] [05:31:02] NOTICE> [TopVoter] No update available! :)
```

**Comment by Aericio** [comment]
Are you sure your API key is in ' '?
ex: `API-Key: '3921uej19x1hdi'`

**Comment by Ishannaik** [comment]
yep

**Comment by Ishannaik** [comment]
API-Key: '*****'
its in the ' '

**Comment by SalmonDE** [comment]
@Ishannaik The line "Raw:" outputs what the serverlist returned, and it says "Error: no server key" which means there really wasn't a server key given.

Could you try putting your key inside " "? I'm really not sure why this issue occurs

**Comment by Ishannaik** [comment]
Worked THANKS BRO

**Comment by SalmonDE** [comment]
Nice to hear it worked @Ishannaik ! Could you try this, @NycuRO and @DKQoo2 ? I'll close this issue for now.

**Comment by Ishannaik** [comment]
btw when i try to change colour of the players Text: "{player} ยง4{votes}" it says same error and with Header too i cant seem to change it

**Comment by Ishannaik** [comment]
btw no thats not the issue when ever u try to add a colour  in the header or the text
it causes the error i think its because of the default green and orange colour?

**Comment by SalmonDE** [comment]
@Ishannaik No I think that means the config file gets corrupted when you save it with these characters.

**Comment by Ishannaik** [comment]
yea pls fix that

**Comment by SalmonDE** [comment]
@Ishannaik I think this is not possible (or not nice). A corrupted config should be deleted and replaced by a new one generated by the plugin.

**Comment by Ishannaik** [comment]
but i cannot change the colours of the text because of this bug

**Comment by SalmonDE** [comment]
@Ishannaik Could you check in what character encoding your config file is saved? Is it UTF-8?

**Comment by Ishannaik** [comment]
what is that?

**Comment by Ishannaik** [comment]
how do i see what code is that?

**Comment by SalmonDE** [comment]
@Ishannaik With programs like NotePad++

**Comment by Ishannaik** [comment]
i did encode in UTF-8 And its same

**Comment by Ishannaik** [comment]
Error *Sigh*
`
Notice: Undefined variable: apis in phar:///root/Tests/plugins/TopVoter.phar/src/SalmonDE/Updater/UpdateManager.php on line 63
[Tesseract] [15:08:30] WARNING> [TopVoter] An update is available but the API version of your server isn't supported by it.
[Tesseract] [15:08:30] WARNING> [TopVoter] API version of the server: 3.0.1
[Tesseract] [15:08:30] WARNING> [TopVoter]
`

**Comment by SalmonDE** [comment]
@Ishannaik This actually isn't an error but a warning that an update is available, but the API version of your server software is **unsupported**. I added this because I @only code with pmmp. I cannot test my plugins on every software and adjust it.

But the undefined apis variable is a bug made by me, thanks! :D

**Comment by SalmonDE** [comment]
@Ishannaik Also, could you tell me what operating system you run your server on? Windows, Linux, Android ...

**Comment by SlothyOne** [comment]
```
#Position of the floating text particle
Pos:
  X: 121
  "Y": 9
  Z: 212
#Worlds which will show the particle
Worlds: [Spawn]
#API-Key of your server provided by minecraftpocket-servers.com
API-Key: "(API code removed by @Aericio)"
#Amount of voters who shall be shown (Max: 500)
Amount: 5
#Update interval of the query to the server in seconds
#SHOULD BE ATLEAST 180! OUTPUT IS CACHED FOR 3 MINUTES!
Update-Interval: 180
#Header of the floating text particle
Header: "Top voters of the month <3"
#Text for every row after the header
Text: "{player} §9{votes}"
#Enable automatically updating to new versions
Auto-Update: true
``` 
im having trouble setting this up..this the config i edited,did i miss something?

**Comment by Ishannaik** [comment]
Linux

**Comment by SalmonDE** [comment]
@Ishannaik Can you give me the output of `file -bi config.yml`?

**Comment by SalmonDE** [comment]
@RyanClarke2 What exactly isn't working for you?

**Comment by SlothyOne** [comment]
im not sure..it looks all good for the most part,i dont see any errors or anything.it just isnt showing the floating text when i enter the server.

**Comment by SalmonDE** [comment]
@RyanClarke2 Is your world named Spawn and did you type in the correct coordinates? And I'd like you to create an own issue with your problem to keep the overview, because this issue already is full of comments.

**Comment by Ishannaik** [comment]
sorry i wasnt on these days but how do i get the outupt

**Comment by Aericio** [comment]
@Ishannaik I believe you do `file -bi config.yml` where TopVoter's config files are.

**Comment by Ishannaik** [comment]
uh in the console?

**Comment by Aericio** [comment]
You're using Linux right? Open terminal (not pocketmines), `cd` into where TopVoter's configuration files are, and run that command in terminal.

**Comment by Ishannaik** [comment]
kk

**Comment by Ishannaik** [comment]
text/plain; charset=utf-8
