### ISSUE TITLE
Uhm....

### ISSUE THREAD

**Issue by Leejit** [SalmonDE/TopVoter#17]
![screenshot_20170330-154611](https://cloud.githubusercontent.com/assets/17371144/24523188/3716da74-1560-11e7-9841-98fbb7901252.png)

this shouldn't be like this, I don't think....

**Comment by SalmonDE** [comment]
Can you look for an error message? Or can you give me a part of your server.log file, where this occurs?

**Comment by Leejit** [comment]
well, the screenshot shows what my console log would show.... the
screenshot is the error I get.

just shows ERROR then something about raw...and shows all that in console.

**Comment by SalmonDE** [comment]
@LordJoshie This still doesn't seem like the full error message

**Comment by Leejit** [comment]
top to bottom, it repeats itself... this is the clip from bottom, and
beginning.

**Comment by SalmonDE** [comment]
@LordJoshie As you can see [here](https://github.com/SalmonDE/TopVoter/blob/master/src/SalmonDE/TopVoter/Tasks/QueryServerListTask.php#L44) there actually have to be more messages. The one in your picture is just the last one. If there are not I'd still be glad if you could send me more of the errors, perhaps I see something useful in the others

**Comment by Aericio** [comment]
Does this problem still persist?

**Comment by Leejit** [comment]
for me it hasnt. it can be closed

**Comment by Aericio** [comment]
Okay. If it happens again, then you can make a new issue / update this one.
