### ISSUE TITLE
Error message > Plugin isnt Green ! It is Red!

### ISSUE THREAD

**Issue by PluginBOXone** [SalmonDE/TopVoter#18]
Error in Console:  [Server thread/CRITICAL]: ClassNotFoundException: "Class SalmonDE\Updater\UpdateManager not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Version: 1.0.5 Alpha
Server Version: BluLight
Server OS: Linux / Debian 8

**Comment by Aericio** [comment]
That's because TopVoter needs the updater files to run, but the updater files are not in the plugin. Downloading it as .zip doesn't add the submodule, so that is probably why. Instead, download the latest build [here.](https://github.com/SalmonDE/TopVoter/releases)

**Comment by SalmonDE** [comment]
He is right, you downloaded the plugin from the wrong location.
