### ISSUE TITLE
Doesnt load

### ISSUE THREAD

**Issue by xXSirGamesXx** [SalmonDE/TopVoter#19]
SO I added the api key correctly but the plugin never loads the text.
I get this error:
`Notice: Undefined variable: err in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\Updater\Utils.php on line 11

Notice: Undefined variable: err in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\Updater\Utils.php on line 19

Notice: Undefined variable: err in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\Updater\Utils.php on line 19

Notice: Undefined index: version in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\Updater\UpdateManager.php on line 25
[15:49:29] [Server thread/NOTICE]: [TopVoter] I'm up to date! :)

Notice: Undefined variable: err in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\TopVoter\Tasks\QueryServerListTask.php on line 16
[15:49:33] [Server thread/INFO]: [HungerGames] All games have been loaded! At least that's what I think :p

Notice: Undefined variable: err in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\TopVoter\Tasks\QueryServerListTask.php on line 18

Notice: Undefined variable: err in C:\Users\xXSir\Downloads\BCN\plugins\TopVoter-master\src\SalmonDE\TopVoter\Tasks\QueryServerListTask.php on line 19
[15:49:34] [Server thread/WARNING]: [TopVoter] Error while processing data from the serverlist!
[15:49:34] [Server thread/ERROR]: [TopVoter]
[15:49:34] [Server thread/ERROR]: [TopVoter] Raw: {
        "name":"FrontierPE Factions",
        "address":"frontierpe.cf",
        "port":"19132",
        "month":"201704",
        "voters": [
                                {
                "nickname":"xxsirbutterxx",
                "votes":"1"                             }                       ]
}

`

**Comment by Aericio** [comment]
Server software issue, you need to use pmmp for TopVoter to work correctly.

**Comment by SalmonDE** [comment]
Due to recent changes to the Utils::getURL() function in pmmp I edited this plugin, which broke compatibility with other software than pmmp. A solution would be to use an older release like [this one](https://github.com/SalmonDE/TopVoter/releases/tag/untagged-935d8392f487433c7d16)
