### ISSUE TITLE
Top costumizable

### ISSUE THREAD

**Issue by ghost** [SalmonDE/TopVoter#2]
@SalmonGER aka Salami ,you can add top 1-10 FloatingText?

Top 1 - {name}
Top 2 - {name}
... with max costumizable in config.yml?

E.g.: In config.yml exist : limit.top: 10. For this show :

Top 1 - {name}
Top 2 - {name}
...
Top 10 - {name}

For : limit.top: 3, show:
Top 1 - {name}
Top 2 - {name}
Top 3 - {name}

You can add? :)

**Comment by NycuRO** [comment]
Again exist :)))))))) Thx again
