### ISSUE TITLE
Error while processing data from the serverlist!

### ISSUE THREAD

**Issue by xXRyzen** [SalmonDE/TopVoter#20]
Getting this error below on console after every update event, and in game floating votes text wont display, any help on this?

```
2017-05-01 [Tesseract] [17:20:49] WARNING> [TopVoter] Error while processing data from the serverlist!
2017-05-01 [Tesseract] [17:20:49] ERROR> [TopVoter]
2017-05-01 [Tesseract] [17:20:49] ERROR> [TopVoter] Raw: {
"name":"MineZoneRP",
"address":"minezonerp.com",
"port":"19132",
"month":"201705",
"voters": [
{
"nickname":"RiversSon_Zero",
"votes":"1"	},	{
"nickname":"LeMatrix",
"votes":"1"	},	{
"nickname":"Bruh_itz_Alen",
"votes":"1"	},	{
"nickname":"xXchloroboneXx",
"votes":"1"	},	{
"nickname":"lklahm",
"votes":"1"	}	]
}
```

**Comment by SalmonDE** [comment]
Thanks for reporting, I will look into this. Can you tell me where you downloaded the plugin from? (Or better, which release) I'd like to know which version you use.

**Comment by xXSirGamesXx** [comment]
I got the same error. But I'm using a different software called Genisys3. Same concept of Tesserract. I'm gonna port the new Utils.php into my software and see if this plugin will work. If you want more info go to github.com/frontierdevs/Genisys3 I will update it tomarrow.

**Comment by xXRyzen** [comment]
I downloaded directly from https://github.com/SalmonDE/TopVoter and this was just earlier today that i downloaded it. and thanks for the quick response!

**Comment by Aericio** [comment]
From the releases tab? Or .zip?

**Comment by SalmonDE** [comment]
@xXSirGamesXx Sorry but I don't understand your comment. The error seems to be not related to the server software, so I decided to accept the issue and look into it, he/she's not making it difficult for me.

**Comment by xXSirGamesXx** [comment]
Ok got it, sorry.

**Comment by xXRyzen** [comment]
From the green "Download Zip" tab @Aericio 
(version: 2.1.0)

**Comment by SalmonDE** [comment]
@FienixEC Are you using any other plugins from me?

**Comment by xXRyzen** [comment]
@SalmonDE Just your FishyUpdater plugin which you may have seen i accidentally posted this issue there

**Comment by Aericio** [comment]
FishyUpdater isn't a plugin...  its files for the plugin.

**Comment by SalmonDE** [comment]
@FienixEC Can you try again with a version downloaded on [this page](https://github.com/SalmonDE/TopVoter/releases)?

**Comment by xXRyzen** [comment]
@SalmonDE  Same issue, although when i first loaded the .phar in the link you provided i got this error on console, with a server crash and no crash report.

2017-05-04 [Tesseract] [02:47:57] CRITICAL> Error: "Call to a member function close() on null" (EXCEPTION) in "/plugins/MineAuth/src/SAM/SAM(526) : eval()'d code(2) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code" at line 1

**after a second server restart, server started fine, with same "Error while processing data from the serverlist"

***** @SalmonDE  do you have kik? if you do send me a message at Fienixic pls****

**Comment by SalmonDE** [comment]
@FienixEC The crash you described seems to be caused by aplugin called MineAuth, not TopVoter.
So it still occurs for you?

**Comment by xXRyzen** [comment]
@salmonde no it only happened that one time after i switched from the TopVoter src to the .phar, hasnt occured since issue mat have been unrelated, i apologize if so, however im getting the same issue as before

**Comment by xXRyzen** [comment]
A good friend of mine, also my host, was able to run a debug on this and came back with these error results, which are specific to my issue, which should give you a better direction towards solving the problem. Hope it helps, and again thanks for your time in helping solve this in a timely manner!

```
2017-05-04 [Tesseract] [21:37:42] ERROR> [TopVoter] error1: 
2017-05-04 [Tesseract] [21:37:42] ERROR> [TopVoter] error2: Array
2017-05-04 [Tesseract] [21:37:42] ERROR> [TopVoter] error3: 
2017-05-04 [Tesseract] [21:37:42] WARNING> [TopVoter] Error while processing data from the serverlist!
2017-05-04 [Tesseract] [21:37:42] ERROR> [TopVoter] 
2017-05-04 [Tesseract] [21:37:42] ERROR> [TopVoter] Raw: {
"name":"MineZoneRP",
"address":"minezonerp.com",
"port":"19132",
"month":"201705",
"voters": [
{
"nickname":"Kaneki_kun",
"votes":"4" }, {
"nickname":"Cinderrr",
"votes":"4" }, {
"nickname":"MonkeyDLuffy ",
"votes":"4" }, {
"nickname":"Br0k3nSm1L3",
"votes":"4" }, {
"nickname":"ZaneW",
"votes":"4" } ]
}

$inst->getLogger()->error('error1: '. $this->getResult()['success']);
$inst->getLogger()->error('error2: '. $inst->getVoters());
$inst->getLogger()->error('error3: '. $this->getResult()['voters']);
```

**Comment by MattWAnderson** [comment]
How does this data work for GetResult() when there is no getResult function in the plugin for it to call on?

**Comment by Aericio** [comment]
@FienixEC What host are you using?

**Comment by xXRyzen** [comment]
@Aericio Its a private dedicated server host, its not like a hosting company like netherbox or cubedhost, its hosted privately

**Comment by Aericio** [comment]
Just to test, can you open up all ports on your system? (pretty sure that doesn't matter but just try)

**Comment by MattWAnderson** [comment]
No, we cannot do that. It is getting the RAW data fine so there is no issue with the collecting data. The issue  has to be related to how the plugin is using data. The plugin is calling on getResults however there is no getResults function or listing of the data key "Voters" for it to collect data for the plugin. we have tested a manual array and this works, however as shown above it is returning NULL data as the getResults isn't valid.

**Comment by SalmonDE** [comment]
@MattWAnderson I'm pretty sure AsyncTask::getResult() does exist, it's predefined by PocketMine, but you're right. Collecting the data works, using it doesn't.

**Comment by SalmonDE** [comment]
Can you try adding echo $e->getMessage(); here:
https://github.com/SalmonDE/TopVoter/blob/master/src/SalmonDE/TopVoter/Tasks/QueryServerListTask.php#L31
Then start the server again and give me the output of the new message. :)

**Comment by SalmonDE** [comment]
This error seems to be caused by an exception caught in the task, however I'd like to confirm that, but I don't encounter this issue (yet?)

**Comment by SalmonDE** [comment]
Hmm, actually, can you tell me which exact version of Tesseract you're using?

**Comment by SalmonDE** [comment]
This issue was caused by server software incompatibility. Tesseract does not support features which this plugin uses and that causes the plugin to throw an exception on it's own.

I'm sorry but I'm not going to add a check for the server software, it doesn't seem nice to me.

**Comment by SalmonDE** [comment]
However I can predefine $err, I can't say that it will work as Tesseract only supports three arguments in Utils::getURL() and not four, but it's worth a try.

**Comment by kabluinc** [comment]
Having same issue on PMMP since 1.1

**Comment by Aericio** [comment]
@kabluinc Can you send a paste of it?

**Comment by kabluinc** [comment]
`[18:03:53] [Server thread/WARNING]: [TopVoter] Error while processing data from the serverlist!
[18:03:53] [Server thread/ERROR]: [TopVoter]
[18:03:53] [Server thread/ERROR]: [TopVoter] Raw: {
        "name":"GamesCube",
        "address":"gamescube.tk",
        "port":"19132",
        "month":"201706",
        "voters": [
                                {
                "nickname":"player1",
                "votes":"5"                             }                       ]
}
`

**Comment by kabluinc** [comment]
Worked fine before the PMMP master branch updated to 1.1.

**Comment by MattWAnderson** [comment]
This is the root issue in the PMMP: I removed the update check and the plugin runs fine on the latest PMMP.

```
    public static function checkVersion(Plugin $plugin, array $data){
//do nothing
    }
```

**Comment by kabluinc** [comment]
@MattWAnderson Where is this code at?

**Comment by SalmonDE** [comment]
@MattWAnderson The updater shouldn't affect the query task at all. Can you prove with tests that this is the cause?

As kabluinc's error message shows, it seems to be a caught exception with no message in it.

**Comment by SalmonDE** [comment]
Should work fine in a14fe2698916b699b313e359beb3d41e2d145ea7 now
