### ISSUE TITLE
Bugggggggg

### ISSUE THREAD

**Issue by TaiXeko** [SalmonDE/TopVoter#21]
[CRITICAL] ErrorException: "yaml_parse(): reading error encountered during parsing: control characters are not allowed (line 1, column 1)" (EXCEPTION) in "/src/pocketmine/utils/Config" at line 143

**Comment by SalmonDE** [comment]
Can you provide the content of your config file?

**Comment by TaiXeko** [comment]
okey

**Comment by TaiXeko** [comment]
[https://secufiles.com/4Ypx/TopVoter_v2.2.1.phar](url)

**Comment by SalmonDE** [comment]
I meant your config.yml file

**Comment by TaiXeko** [comment]
Removed because of Key exposure

**Comment by SalmonDE** [comment]
It seems like instead of § for colour codes you inserted specials characters. Please fix your config file and make sure that you really wrote e.g. §4.

**Comment by TaiXeko** [comment]
why key not found

**Comment by SalmonDE** [comment]
Check your config for that
