### ISSUE TITLE
Suport Please

### ISSUE THREAD

**Issue by TaiXeko** [SalmonDE/TopVoter#22]
Hello again! sorry to bother ! Why do not you show topvote with FloatingText so people will see how this plugin can see TopVote!

**Comment by SalmonDE** [comment]
This plugin is about showing the players who voted the most on a floating text already. Is it not working for you?

**Comment by TaiXeko** [comment]
xyz ?

**Comment by TaiXeko** [comment]
#Position of the floating text particle
Pos:
  X: 84.5
  "Y": 72
  Z: 83.7
#Worlds which will show the particle
Worlds: sb
#API-Key of your server provided by minecraftpocket-servers.com
API-Key: "U6beJvw98HAtJwMaCAPTiJjD4PmA4O3o91R"
#Amount of voters who shall be shown (Max: 500)
Amount: 10
#Update interval of the query to the server in seconds
#SHOULD BE ATLEAST 180! OUTPUT IS CACHED FOR 3 MINUTES!
Update-Interval: 180
#Header of the floating text particle
Header: "-=-Top voters of the month-=-"
#Text for every row after the header
Text: "{player}->{votes}"

**Comment by TaiXeko** [comment]
Thank you for it already works. Can you write the Village Shop Plugin?


Vào 20-07-2017 0:03, "SalmonDE" <notifications@github.com> đã viết:

**Comment by SalmonDE** [comment]
Sorry, I'm not accepting requests in the issue tracker of TopVoter. Please ask on the pmmp forums for requests.
https://forums.pmmp.io/forums/requests/
