### ISSUE TITLE
Error reading ca cert file

### ISSUE THREAD

**Issue by HiggsInc** [SalmonDE/TopVoter#23]
Hey mate, any advise for the following:
[Server thread/ERROR]: [TopVoter] Error: Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x3E00) PK - Read/write of file failed

Been using this plugin for a while however its started producing this error a few API versions ago. Any suggestions on solving this?

Server Details:
server is running [PocketMine-MP 1.7dev-435]「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.5.15 beta (protocol version 141)

plugin taken from the following link
https://poggit.pmmp.io/r/13192/TopVoter_dev-20.phar

**Comment by SalmonDE** [comment]
You seem to have a linux system. Can the file located in /etc/ssl/certs/ca-certificates.crt be opened by the mcbe server?

**Comment by HiggsInc** [comment]
Unfortunately not in this instance as that file does not exist

**Comment by SalmonDE** [comment]
The server tries to open that file and because it fails, it also can't connect to the serverlist website.

This is probably because the file is needed by curl for https.

**Comment by HiggsInc** [comment]
No problem. I've created a certificate which had to be labelled "ca-certificates.crt" in order for this to work

Thanks again

**Comment by CupidonSauce173** [comment]
How do I fix this issue if I run on CentOS 7 ? @HiggsInc

**Comment by SalmonDE** [comment]
For future reference:
On Debian systems installing ca-certificates seems to have fixed the problem for someone:
`apt-get install ca-certificates`
