### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ShotDead7297** [SalmonDE/TopVoter#24]
erver thread/DEBUG #1 src/pocketmine/utils/Config(155): yaml_parse(string #Position of the floating text particle..Pos:..  X: 12..  "Y": 22..  Z: 35..#Worlds which will show the particle..Worlds: [world1, world]..#API-Key of your server provided by minecraftpocket-servers.com..API-Key: *CENSORED*..#Amount of voters who shall be shown (Max: 500)..Amount: 19..#Update interval of the query to the server in seconds..#SHOULD BE ATLEAST 180! OUTPUT IS CACHED FOR 3 MINUTES!..Update-Interval: 180..#Header of the floating text particle..Header: "Top voters of the month <3"..#Text for every row after the header..Text: "{player} ..9{votes}")
07.06 10:04:59 [Server] Server thread/DEBUG #2 src/pocketmine/utils/Config(86): pocketmine\utils\Config->load(string /plugins/TopVoter/config.yml, integer -1, array Array())
07.06 10:04:59 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginBase(264): pocketmine\utils\Config->__construct(string /plugins/TopVoter/config.yml)
07.06 10:04:59 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginBase(244): pocketmine\plugin\PluginBase->reloadConfig()
07.06 10:04:59 [Server] Server thread/DEBUG #5 TopVoter (9).phar/src/SalmonDE/TopVoter/TopVoter(31): pocketmine\plugin\PluginBase->getConfig()
07.06 10:04:59 [Server] Server thread/DEBUG #6 TopVoter (9).phar/src/SalmonDE/TopVoter/TopVoter(21): SalmonDE\TopVoter\TopVoter->initParticle()
07.06 10:04:59 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/PluginBase(90): SalmonDE\TopVoter\TopVoter->onEnable()
07.06 10:04:59 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PharPluginLoader(127): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
07.06 10:04:59 [Server] Server thread/DEBUG #9 src/pocketmine/plugin/PluginManager(576): pocketmine\plugin\PharPluginLoader->enablePlugin(SalmonDE\TopVoter\TopVoter object)
07.06 10:04:59 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1919): pocketmine\plugin\PluginManager->enablePlugin(SalmonDE\TopVoter\TopVoter object)
07.06 10:04:59 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1905): pocketmine\Server->enablePlugin(SalmonDE\TopVoter\TopVoter object)

**Comment by ShotDead7297** [comment]
what do i do about this

**Comment by SalmonDE** [comment]
Your key must be encapsulated inside of the “ symbol

After you've corrected the placement of your api key and every other potential flaw in your configuration file, this error shouldn't occur anymore.
