### ISSUE TITLE
Error reading ca cert file

### ISSUE THREAD

**Issue by CupidonSauce173** [SalmonDE/TopVoter#26]
[Server thread/WARNING]: [TopVoter] Error while processing data from the serverlist!
[Server thread/ERROR]: [TopVoter] Error: Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x3E00_ PK - Read/write of file failed

pocketmine information : dev 1.7 build 1001 API 3.0.0-ALPHA12

**Comment by CupidonSauce173** [comment]
I run on CentOS 7.

**Comment by Aericio** [comment]
@SalmonDE Maybe we should let them define the path to their certificate instead, since some OS have them in different places?

**Comment by SalmonDE** [comment]
As far as I can tell this is an issue with your php/system configuration. TopVoter is not using any certificate files directly.

However, that file seems to be needed by curl to establish a https connection to the serverlist, hence why it occurs when TopVoter tries to fetch data from it.

**Comment by SalmonDE** [comment]
For future reference:
On Debian systems installing ca-certificates seems to have fixed the problem for someone:
`apt-get install ca-certificates`
