### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SuperAdam47** [SalmonDE/TopVoter#29]
![image](https://user-images.githubusercontent.com/16169771/43922673-17598a6a-9c28-11e8-95a0-c76aec193932.png)

**Comment by SalmonDE** [comment]
Your config is outdated. Make sure it looks like the default one:
https://github.com/SalmonDE/TopVoter/blob/master/resources/config.yml

**Comment by SuperAdam47** [comment]
ok.
