### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ShotDead7297** [SalmonDE/TopVoter#34]
27.10 17:35:42 [Server] Server thread/CRITICAL Could not execute task SalmonDE\TopVoter\Tasks\UpdateVotesTask: Declaration of SalmonDE\TopVoter\Tasks\QueryServerListTask::onCompletion(): void should be compatible with pocketmine\scheduler\AsyncTask::onCompletion(pocketmine\Server $server)
27.10 17:35:42 [Server] Server thread/CRITICAL ErrorException: "Declaration of SalmonDE\TopVoter\Tasks\QueryServerListTask::onCompletion(): void should be compatible with pocketmine\scheduler\AsyncTask::onCompletion(pocketmine\Server $server)" (EXCEPTION) in "TopVoter-master/src/SalmonDE/TopVoter/Tasks/QueryServerListTask" at line 78
27.10 17:35:42 [Server] Server thread/DEBUG #0 vendor/pocketmine/spl/BaseClassLoader(126): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string Declaration of SalmonDE\TopVoter\Tasks\QueryServerListTask::onCompletion(): void should be compatible with pocketmine\scheduler\AsyncTask::onCompletion(pocketmine\Server $server), string /plugins/TopVoter-master/src/SalmonDE/TopVoter/Tasks/QueryServerListTask.php, integer 78, array Array())
27.10 17:35:42 [Server] Server thread/DEBUG #1 vendor/pocketmine/spl/BaseClassLoader(126): include()
27.10 17:35:42 [Server] Server thread/DEBUG #2 (): BaseClassLoader->loadClass(string SalmonDE\TopVoter\Tasks\QueryServerListTask)
27.10 17:35:42 [Server] Server thread/DEBUG #3 TopVoter-master/src/SalmonDE/TopVoter/Tasks/UpdateVotesTask(27): spl_autoload_call(string SalmonDE\TopVoter\Tasks\QueryServerListTask)
27.10 17:35:42 [Server] Server thread/DEBUG #4 src/pocketmine/scheduler/TaskHandler(163): SalmonDE\TopVoter\Tasks\UpdateVotesTask->onRun(integer 1)
27.10 17:35:42 [Server] Server thread/DEBUG #5 src/pocketmine/scheduler/TaskScheduler(203): pocketmine\scheduler\TaskHandler->run(integer 1)
27.10 17:35:42 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginManager(667): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1)
27.10 17:35:42 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2503): pocketmine\plugin\PluginManager->tickSchedulers(integer 1)
27.10 17:35:42 [Server] Server thread/DEBUG #8 src/pocketmine/Server(2256): pocketmine\Server->tick()
27.10 17:35:42 [Server] Server thread/DEBUG #9 src/pocketmine/Server(2134): pocketmine\Server->tickProcessor()
27.10 17:35:42 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1700): pocketmine\Server->start()
27.10 17:35:42 [Server] Server thread/DEBUG #11 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
27.10 17:35:42 [Server] Server thread/DEBUG #12 /pmmp_1573_1.7.0.phar(1): require(string phar:///pmmp_1573_1.7.0.phar/src/pocketmine/PocketMine.php)

**Comment by SalmonDE** [comment]
Download the release version from Poggit: https://poggit.pmmp.io/p/TopVoter/3.1.0
