### ISSUE TITLE
Does not work at all.

### ISSUE THREAD

**Issue by LiaamDev** [SalmonDE/TopVoter#35]
Version 3.1.0 for API 3.0.0-3.6.1. Plugin just does not work despite putting in correct information coordinates in config.yml.

**Comment by Aericio** [comment]
We don't have version 3.1.0 for API 3.0.0. Version 3.1.0 uses API 4.0.0.

**Comment by LiaamDev** [comment]
Not according to poggit. Poggit says version 3.1.0 is for APIs 3.0.0-3.6.1 - which versions of the plugin are for 3.0.0 API?

**Comment by SalmonDE** [comment]
Cannot reproduce using PMMP 3.6.2 and TopVoter poggit release 3.1.0.
Please check your configuration or elaborate the situation.

![image](https://user-images.githubusercontent.com/15953947/53088941-76780400-350b-11e9-9d8f-cfc740c14500.png)

**Comment by Aericio** [comment]
> Not according to poggit. Poggit says version 3.1.0 is for APIs 3.0.0-3.6.1 - which versions of the plugin are for 3.0.0 API?

Ah, there was another branch. https://github.com/SalmonDE/TopVoter/tree/api-3.0.0

@SalmonDE would be kinda nice if two different api versions would have different plugin versions lol

**Comment by LiaamDev** [comment]
I’m sure I’ve got the 3.0.0 API Version as my server has no trouble running it. It just doesn’t work.

**Comment by LiaamDev** [comment]
Apologies. The plugin DOES infact work.

**Comment by SalmonDE** [comment]
@Aericio I was planning to bump the plugin version in the master branch as soon as there's a stable release  of pmmp 4.0

@LiaamDev I'm glad the plugin now works for you. ;)
