### ISSUE TITLE
Other plugin with GameTrack

### ISSUE THREAD

**Issue by ghost** [SalmonDE/TopVoter#6]
Hi again Salami, @SalmonGER .  You can create other plugin with TopOnlineTime.

For top online time on server ,players ? :) Using GameTracker,have support OnlineTime :)

**Comment by aquaminer** [comment]
Fantastic idea it would be interesting to see

**Comment by ghost** [comment]
Or Items command. Switch item from inventory and execute command. Like LBSG

**Comment by SalmonDE** [comment]
Sorry, I don't understand what you mean @NycuRO.
What TopOnlineTime?

**Comment by ghost** [comment]
@SalmonGER You can create new plugin, " TopOnlineTime " ?

**Comment by Aericio** [comment]
He could just add it into StatsPE and make /statstop or something like that.
ex: /statstop [kills/deaths/onlinetime/etc]
