### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by padreon** [SalmonDE/TopVoter#7]
[Server] Server thread/CRITICAL Error: "Call to a member function getLogger() on null" (EXCEPTION) in "/TopVoter-master.phar/src/SalmonDE/Tasks/QueryServerListTask" at line 46

**Comment by Aericio** [comment]
What servercore are you runnibg on?

**Comment by SalmonDE** [comment]
Did you rename the plugin?

**Comment by Aericio** [comment]
@SalmonGER He probably compiled it himself.

**Comment by padreon** [comment]
@SalmonGER I just took the name of his zip

**Comment by Aericio** [comment]
Still getting it?

**Comment by Aericio** [comment]
@padrone21 Do you still get it? If not, I'm closing this.
